name: Checks

on: [push]

jobs:  # Corrected from 'jops'
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest  # Use latest unless a specific version is needed
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"  # Fixed dashes

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"  # Fixed dashes
